
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './workaround-types';

const SUPABASE_URL = "https://vkvyucifczyhfycdljvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdnl1Y2lmY3p5aGZ5Y2RsanZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTczODMsImV4cCI6MjA2MjQ3MzM4M30.v3JwLaOqH0md1opSTDtVVgnNZbu0T_uopEVAv4VKofI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
