// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nasxwdsezjvsifpuntth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hc3h3ZHNlemp2c2lmcHVudHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTI5MTcsImV4cCI6MjA2MjYyODkxN30.Fl4Cp3EznVgHXMpKi0PEf9E0enqJZr8Va6Vi-_pwK2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);